on: push

name: Test builds

jobs:
  build_win:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install CUDA
        run: |
          Invoke-WebRequest http://developer.download.nvidia.com/compute/cuda/11.0.1/network_installers/cuda_11.0.1_win10_network.exe -OutFile .\cuda_setup.exe
          cmd /c start /wait .\cuda_setup.exe -s nvcc_11.0 cudart_11.0 nvrtc_dev_11.0
        shell: powershell
      - name: Build project on Windows
        run: |
          dir "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA"
          cmake . -G "Visual Studio 16 2019" -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0"
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
          .\MSBuild.exe /p:Configuration=Release $Env:GITHUB_WORKSPACE\xmrig-cuda.sln
        shell: cmd
